#!/bin/perl

use strict;
use Net::DNS;

my $resolver = Net::DNS::Resolver->new;
my $answer;

print "<table>\n  <tr><th>Domain</th><th>DNS</th><th>WWW</th><th>MX</th></tr>\n";

foreach my $domain (@ARGV) {

    print "  <tr>\n    <td><a href=\"http://www.$domain/\">$domain</a></td>\n";

    check_for_NS($domain);
    check_for_AAAA("www." . $domain, 1);
    check_for_MX($domain);
    print "  </tr>\n";
}

print "</table>\n";

sub check_for_NS {
    my ($name) = @_;
    my $count = 0;

    # Find the list of MX records for a name
    my $query = $resolver->search($name, "NS");

    if ($query) {
	foreach my $record ($query->answer) {
	    # for each NS record, find at least one that has an IPv6 address
	    $count += check_for_AAAA($record->nsdname);
	}
    }
    if ($count > 0) {
	Succeed($count);
	return $count;
    }
    # if we got here for any reason, we've failed
    Fail();
    return 0;
}

sub check_for_MX {
    my ($name) = @_;
    my $count = 0;

    # Find the list of MX records for a name
    my $query = $resolver->search($name, "MX");

    if ($query) {
	foreach my $record ($query->answer) {
	    # for each MX record, find at least one that has an IPv6 address
	    $count += check_for_AAAA($record->exchange);
	}
    }
    if ($count > 0) {
	Succeed($count);
	return $count;
    }
    # if we got here for any reason, we've failed
    Fail();
    return 0;
}

sub check_for_AAAA {
    my ($name, $printresults) = @_;
    my $count = 0;
    
    # test for an AAAA record for whatever was passed in
    my $query = $resolver->search($name, "AAAA");
    
    if ($query) {
	foreach my $record ($query->answer) {
	    next unless $record->type eq "AAAA";
	    Verbose("found an AAAA record for $name: $answer");
	    $count++;
	}
	if ($count > 0) {
	    if ($printresults) {
		Succeed($count);
	    }
	    return $count;
	}
    } else {
	Warn("Query failed: ", $resolver->errorstring, "\n");
    }
    if ($printresults) {
	Fail();
    }
    return 0;
}

sub Succeed {
    my ($addr) = @_;

    print "    <td bgcolor=\"40ff40\">$addr</td>\n";
}

sub Fail {
    my ($record) = @_;

    print "    <td bgcolor=\"red\">0</td>\n";
}

sub Warn {
    print STDERR @_;
}

sub Verbose {
    # print STDERR @_;
}
