ipv6day -- Get The Results Yourself

* Objective

  The ipv6day script is a very simple perl program that tests sites for
  DNS entries for IPv6 data.  Most importantly, it doesn't just check
  for an AAAA record for the web server.  That's not enough to be
  considered truly IPv6 enabled.  At a minimum, the DNS servers for a
  given domain must be accessible over IPv6 as well.  Since EMail is
  still a fairly popular transport thees days, the script also checks
  for a valid IPv6 MX record.

  The other big changes coming to the net involve DNS Security
  (DNSSEC).  Since these domains are updating for IPv6, they certainly
  should be doing DNSSEC at the same time.  So I'm querying for two
  different types of critical DNSSEC data as well: whether the domain
  is hosting a DNSKEY and whether the domain's parent has a DS record
  pointing to the domain's key.

  Many more tests could be done for both IPv6 and for DNSSEC, but the
  script at this time has only striven to produce a simple set of
  tests.

* Usage

  # ./ipv6day [SITES] > results.html
  # favorite-browser rseults.html

  A list of sites that indicated they would participate in the 2011
  World IPv6 Day can be found in "2011-sites.txt" so that this is
  possible:

  # ./ipv6day `cat 2011-sites.txt` > results.html


* Future work

  Any simple program should be subject to feature creep...

  + Maybe make it perform a service availability test too.
  + deal with CNAMEs for MX and NS records
  + make the calls asynchronous so it doesn't take a year to run on a
    long list.
